os: linux
dist: xenial
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'

cache:
  directories:
    - .autoconf
    - $HOME/.m2

before_script:
  - composer install --prefer-dist

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --coverage-clover coverage.xml -- tests; else php vendor/bin/phpunit --testdox -- tests; fi

after_success:
- bash <(curl -s https://codecov.io/bash)
