os: linux
dist: xenial
language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

cache:
  directories:
    - .autoconf
    - $HOME/.m2

before_script:
  - composer install --prefer-dist

script:
  - >
    if [ "$(phpenv version-name | cut -c 1-3)" = "8.0" ]; then
      php vendor/bin/phpunit --testdox -- tests
    else
      XDEBUG_MODE=coverage vendor/bin/phpunit --testdox --coverage-clover coverage.xml -- tests
    fi

after_success:
- bash <(curl -s https://codecov.io/bash)
