language: php
php:
  - '7.3'

directories:
  - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - cd tests/
  - php ../vendor/bin/phpunit --testdox --testsuite Unit

after_success:
- bash <(curl -s https://codecov.io/bash)
