os: linux
dist: xenial
language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

cache:
  directories:
    - .autoconf
    - $HOME/.m2

before_script:
  - composer install --prefer-dist

script:
  - cd tests/
  - php ../vendor/bin/phpunit --testdox -- tests

after_success:
- bash <(curl -s https://codecov.io/bash)
