language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

directories:
  - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - cd tests/
  - php ../vendor/bin/phpunit --testdox tests

after_success:
- bash <(curl -s https://codecov.io/bash)
