on: [ push, pull_request ]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                include:
                    -   operating-system: 'ubuntu-latest'
                        php-versions: '5.6'
                        phpunit-versions: '5.7.26'
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl
                    ini-values: post_max_size=256M, max_execution_time=180
                    coverage: xdebug
                    tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    # Use composer.json for key, if composer.lock is not committed.
                    # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Test with PHPUnit
                env:
                    XDEBUG_MODE: coverage
                run: phpunit --testdox --coverage-clover coverage.xml -- tests

            -   name: Codecov
                uses: codecov/codecov-action@v2
